[package]
name = "reactor_rs_example"
version = "0.1.0"
edition = "2024"

[dependencies]
libc = "0.2.173"
rand = { version = "0.7.3", default-features = false, features = ["std"] }
lazy_static = "1.4"
log = "0.4"
env_logger = "0.11"