[package]
name = "feature_lib"
version = "0.1.0"
edition = "2024"

[features]
default = ["feature_a", "feature_b","logging"]
feature_a = []
feature_b = []
logging = []

[lib]
name = "feature_lib"
path = "src/lib.rs"


